/**
 * Angular Tutorial REST API
 * This is the REST API that is to be used during the Angular Basics course. The API provides the basic functions and elements to build a simple blog. <br/>Building parts of a simple blog webpage are PAGE, ARTICLE and FILE. For simplicity only IMAGES are allowed to be saved. <br/>Usually all methods that don't modify the content will be accessible without authentication. In order to change the content you will have to be authenticated and have the respective user rights to modify the content. User authentication is done via keycloak - an open source user management server. Detailed description will be added later
 *
 * OpenAPI spec version: 1.0
 * Contact: martin.dobrev@akros.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';


export interface ArticleDTO { 
    authorId?: string;
    /**
     * article content as markdown
     */
    content?: string;
    created?: Date;
    deletable?: boolean;
    editable?: boolean;
    featured?: boolean;
    /**
     * parsed article content as html, only available when loading a single article
     */
    htmlContent?: string;
    id?: number;
    imageId?: number;
    publishable?: boolean;
    published?: boolean;
    subtitle?: string;
    title?: string;
    user?: UserDTO;
}
